---
# tasks file for thinpool autoextends

- name: lvm_autoextends | configure lvm autoextends
  template:
    src: thinpool-profile.j2
    dest: /etc/lvm/profile/{{ vg.vgname }}-{{ lv.lvname }}.profile
    owner: root
    group: root
  become: yes
  loop: "{{ vg.lvnames }}"
  loop_control:
    loop_var: lv
  when: >
    (
    (lv is defined and
    lv != 'None') and
    (
    lv.autoextendtreshold is defined and
    lv.autoextendpercent is defined
    )
    )

- name: lvm_autoextends | apply metadata profile
  command: lvchange --metadataprofile {{ vg.vgname }}-{{ lv.lvname }} {{ vg.vgname }}/{{ lv.lvname }}
  become: yes
  loop: "{{ vg.lvnames }}"
  loop_control:
    loop_var: lv
  when: >
    (
    (lv is defined and
    lv != 'None') and
    (
    lv.autoextendtreshold is defined and
    lv.autoextendpercent is defined
    )
    )