---
- name: Converge
  hosts: all
  vars:
    lvm_groups:
      - vgname: non-persistent
        disks:
          - /dev/sdb1
        create: true
        lvnames:
          - lvname: thinpool
            size: 40%VG
            opts: "--wipesignatures y"
            create: true
            metadata: non-persistent/thinpoolmeta
            autoextendtreshold: 80
            autoextendpercent: 20
            filesystem: xfs
            mntp: /var/lib/docker
            mount: true
          - lvname: thinpoolmeta
            size: 10%VG
            opts: "--wipesignatures y"
            create: true
    manage_lvm: true
  tasks:
    - shell: ls /dev
        register: result
    - debug:
        var: result
        verbosity: 2
    - name: "Include lvm"
      include_role:
        name: "ansible-volumes"
